name: Deploy to Cloud Run

on:
  push:
    branches: [ main ]  # Change this if you're using another branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # ✅ Auth using service account JSON key
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    # ✅ Set up gcloud CLI (without service_account_key)
    - name: Set up gcloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    # ✅ Authorize Docker to push to Artifact Registry
    - name: Configure Docker for Artifact Registry
      run: |
        gcloud auth configure-docker us-central1-docker.pkg.dev

    # ✅ Build and push Docker image
    - name: Build and Push Docker image
      run: |
        IMAGE="us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/stock-analyzer-web-app/my-service"
        docker build -t $IMAGE .
        docker push $IMAGE

    # ✅ Deploy to Cloud Run
    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy my-service \
          --image=us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/stock-analyzer-web-app/my-service \
          --region=us-central1 \
          --platform=managed \
          --allow-unauthenticated
