name: Deploy to Cloud Run

on:
  push:
    branches: [ main ]  # or whichever branch you use

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Google Cloud SDK
      uses: google-github-actions/auth@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Configure Docker
      run: gcloud auth configure-docker us-east1-docker.pkg.dev

    - name: Build and push Docker image
      run: |
        IMAGE="us-east1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/stock-analyzer-web-app/my-service"
        docker build -t $IMAGE .
        docker push $IMAGE

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy my-service \
          --image=us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/stock-analyzer-web-app/my-service \
          --region=us-east1 \
          --platform=managed \
          --allow-unauthenticated
